- hosts: consul
  become: yes
  roles:
    - role: consul
      vars:
        dc_name: "sirius"
        consul_ansible_group: "consul"

- name: slave
  hosts: pudg
  become: true
  strategy: linear
  roles:
    - base
    
